apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    app: client
spec:
  containers:
  - name: client
    image: python:3.9
    command: ["/bin/sh", "-c"]
    args:
    - |
      while true; do
        curl http://server-pod:5000 || echo "Server not reachable";
        sleep 5;
      done;
