apiVersion: v1
kind: Pod
metadata:
  name: server-pod
  labels:
    app: server
spec:
  containers:
  - name: server
    image: python:3.9
    command: ["python3", "-m", "http.server", "5000"]
    ports:
    - containerPort: 5000
